import { useEffect, useState } from "react";
import axios from "axios";
import { CalendarDays, Check, ChevronRight, Clock3, Download, GraduationCap, LayoutDashboard, LogOut, MapPin, Plus, Search, Sparkles, Users, X } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const api = axios.create({ baseURL: API, withCredentials: true });

function SignIn({ onLogin }) {
  const [mode, setMode] = useState("login");
  const [form, setForm] = useState({ username: "maya", password: "maya1234", name: "", role: "volunteer", department: "" });
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const submit = async (event) => {
    event.preventDefault(); setBusy(true); setError("");
    try { const body = mode === "login" ? { username: form.username, password: form.password } : { ...form, skills: ["Python", "Design"] }; const { data } = await api.post(`/auth/${mode}`, body); onLogin(data); }
    catch (err) { setError(err.response?.data?.detail || "Please check your details and try again."); }
    finally { setBusy(false); }
  };
  return <main className="auth-shell"><div className="auth-image"><div className="auth-caption"><span className="eyebrow">CAMPUS LIFE, MATCHED</span><h1>Make your mark<br /><em>on campus.</em></h1><p>Find meaningful ways to contribute, meet your people, and leave every event better than you found it.</p></div></div><section className="auth-panel"><div className="brand"><span className="brand-mark"><Sparkles size={17} /></span><span>skill<span>match</span></span></div><div className="auth-copy"><span className="eyebrow">WELCOME BACK</span><h2>{mode === "login" ? "Your next contribution starts here." : "Join the campus network."}</h2><p>{mode === "login" ? "Sign in to discover events built for your strengths." : "Create a student profile and find your fit."}</p></div><form onSubmit={submit} data-testid="auth-form">{mode === "register" && <><Field label="Full name"><input data-testid="register-name-input" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Alex Johnson" required /></Field><Field label="Department"><input data-testid="register-department-input" value={form.department} onChange={e => setForm({ ...form, department: e.target.value })} placeholder="Computer Science" required /></Field><Field label="Role"><select data-testid="register-role-select" value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option value="volunteer">Student volunteer</option><option value="organizer">Event organizer</option></select></Field></>}<Field label="Username"><input data-testid="auth-username-input" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} placeholder="e.g. maya" required /></Field><Field label="Password"><input data-testid="auth-password-input" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="••••••••" required /></Field>{error && <p className="form-error" data-testid="auth-error">{error}</p>}<button className="primary-btn full" data-testid="auth-submit-button" disabled={busy}>{busy ? "Opening your space…" : mode === "login" ? "Enter SkillMatch" : "Create my profile"}<ChevronRight size={17} /></button></form><button className="text-btn" data-testid="auth-mode-toggle" onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); }}>{mode === "login" ? "New to SkillMatch? Create an account" : "Already have an account? Sign in"}</button><p className="demo-hint">Demo access: <b>maya / maya1234</b> · organizer: <b>campusadmin / admin1234</b></p></section></main>;
}

function Field({ label, children }) { return <label>{label}{children}</label>; }

function App() {
  const [user, setUser] = useState(null); const [events, setEvents] = useState([]); const [apps, setApps] = useState([]); const [certificates, setCertificates] = useState([]); const [query, setQuery] = useState(""); const [active, setActive] = useState("discover"); const [modal, setModal] = useState(false); const [toast, setToast] = useState(""); const [loading, setLoading] = useState(true);
  const load = async (current) => { if (!current) return; const [eventRes, extraRes] = await Promise.all([api.get("/events"), api.get(current.role === "volunteer" ? "/certificates" : "/organizer/applicants")]); setEvents(eventRes.data); if (current.role === "volunteer") setCertificates(extraRes.data); else setApps(extraRes.data); };
  useEffect(() => { api.get("/auth/me").then(res => setUser(res.data)).catch(() => {}).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (user) load(user); }, [user]);
  const notify = message => { setToast(message); window.setTimeout(() => setToast(""), 3000); };
  const logout = async () => { await api.post("/auth/logout"); setUser(null); setEvents([]); };
  if (loading) return <div className="loading">Loading your campus…</div>;
  if (!user) return <SignIn onLogin={setUser} />;
  const filtered = events.filter(item => `${item.title} ${item.description} ${item.location} ${item.required_skills.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="app-frame"><Sidebar user={user} active={active} setActive={setActive} certificates={certificates} onLogout={logout} onSwitch={() => setUser({ ...user, role: user.role === "organizer" ? "volunteer" : "organizer" })} /><main className="main-content"><header className="topbar"><div className="mobile-brand"><span className="brand-mark"><Sparkles size={15} /></span> skillmatch</div><div className="topbar-right"><span className="campus-pill"><span className="live-dot" /> Spring semester · 2025</span><div className="avatar small">{user.name[0]}</div></div></header>{active === "discover" && <Discover user={user} events={filtered} query={query} setQuery={setQuery} onCreate={() => setModal(true)} onApply={async item => { try { await api.post(`/events/${item.id}/apply`); notify("You’re on the list — the organizer will be in touch."); load(user); } catch (err) { notify(err.response?.data?.detail || "Could not join this event"); } }} />}{active === "certificates" && <Certificates certificates={certificates} />}{active === "manage" && <Manage apps={apps} onUpdate={async (eventId, username, status) => { await api.patch(`/applications/${eventId}/${username}`, { status }); notify(`Application ${status}.`); load(user); }} onComplete={async (eventId, username) => { try { await api.post(`/events/${eventId}/complete`, { username, hours: 4, notes: "Completed campus contribution" }); notify("Completion recorded — certificate is ready."); load(user); } catch (err) { notify(err.response?.data?.detail || "Could not record completion"); } }} />}{modal && <CreateModal onClose={() => setModal(false)} onCreate={async data => { await api.post("/events", data); setModal(false); notify("Event published to campus."); load(user); }} />}{toast && <div className="toast" data-testid="toast-message"><Check size={17} /> {toast}</div>}</main></div>;
}

function Sidebar({ user, active, setActive, certificates, onLogout, onSwitch }) { return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={17} /></span><span>skill<span>match</span></span></div><div className="side-profile"><div className="avatar">{user.name[0]}</div><div><b>{user.name}</b><small>{user.role === "organizer" ? "Event organizer" : "Student volunteer"}</small></div></div><nav><NavButton active={active === "discover"} test="nav-discover-button" onClick={() => setActive("discover")} icon={<LayoutDashboard size={18} />}>Discover</NavButton>{user.role === "volunteer" && <NavButton active={active === "certificates"} test="nav-certificates-button" onClick={() => setActive("certificates")} icon={<GraduationCap size={18} />}>My certificates {certificates.length > 0 && <i>{certificates.length}</i>}</NavButton>}{user.role === "organizer" && <NavButton active={active === "manage"} test="nav-manage-button" onClick={() => setActive("manage")} icon={<Users size={18} />}>Manage volunteers</NavButton>}</nav><div className="sidebar-bottom"><div className="role-note"><span className="live-dot" /> {user.role === "organizer" ? "Organizer mode" : "Volunteer mode"}<button data-testid="switch-role-button" onClick={onSwitch}><ChevronRight size={14} /></button></div><button className="logout-btn" data-testid="logout-button" onClick={onLogout}><LogOut size={16} /> Sign out</button></div></aside>; }
function NavButton({ active, test, onClick, icon, children }) { return <button className={active ? "nav-active" : ""} data-testid={test} onClick={onClick}>{icon}{children}</button>; }

function Discover({ user, events, query, setQuery, onCreate, onApply }) { return <><section className="welcome"><div><span className="eyebrow">{user.role === "organizer" ? "YOUR CAMPUS, YOUR STAGE" : `GOOD MORNING, ${user.name.split(" ")[0].toUpperCase()}`}</span>{user.role === "organizer" ? <h1>Bring your next idea<br />to <em>life.</em></h1> : <h1>Find where you <em>belong.</em></h1>}<p>{user.role === "organizer" ? "Create events, find the right people, and make every moment count." : "Opportunities that match what you’re good at — and what you want to become."}</p></div><div className="welcome-stat"><b>{events.length}</b><span>active events<br />this semester</span></div></section><section className="hero-strip"><div><span className="eyebrow light">FEATURED THIS WEEK</span><h2>Small actions.<br /><em>Big campus energy.</em></h2><p>Volunteers make the moments people remember.</p><button className="light-btn" data-testid="hero-browse-button" onClick={() => document.getElementById("event-list")?.scrollIntoView({ behavior: "smooth" })}>Browse opportunities <ChevronRight size={16} /></button></div><div className="hero-visual"><div className="hero-date"><b>21</b><span>SEP<br />2025</span></div></div></section><section className="content-section" id="event-list"><div className="section-head"><div><span className="eyebrow">OPEN OPPORTUNITIES</span><h2>Find your next event</h2></div>{user.role === "organizer" && <button className="primary-btn" data-testid="create-event-button" onClick={onCreate}><Plus size={17} /> Create event</button>}</div><div className="filters"><div className="search-box"><Search size={17} /><input data-testid="event-search-input" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search events, skills, or places…" /></div><span className="result-count" data-testid="event-count">{events.length} events</span></div><div className="event-grid">{events.map((item, index) => <EventCard key={item.id} event={item} user={user} onApply={() => onApply(item)} index={index} />)}</div>{events.length === 0 && <div className="empty"><Search size={25} /><b>No events found</b><span>Try a different search term.</span></div>}</section></>; }
function EventCard({ event, user, onApply, index }) { const joined = ["pending", "accepted", "completed"].includes(event.application); return <article className={`event-card card-${index % 3}`} data-testid={`event-card-${event.id}`}><div className="event-card-top"><span className="date-block"><b>{new Date(`${event.date}T12:00:00`).getDate()}</b><small>{new Date(`${event.date}T12:00:00`).toLocaleDateString("en-US", { month: "short" }).toUpperCase()}</small></span><span className="match-badge">{event.match ? <><Sparkles size={12} /> Great match</> : "Open to all"}</span></div><div className="event-info"><span className="event-type">{event.title.includes("Festival") ? "CAMPUS CULTURE" : event.title.includes("Green") ? "COMMUNITY" : "LEARNING"}</span><h3>{event.title}</h3><p>{event.description}</p><div className="event-meta"><span><Clock3 size={14} /> {event.time}</span><span><MapPin size={14} /> {event.location}</span></div></div><div className="event-footer"><div className="skill-list">{event.required_skills.slice(0, 2).map(skill => <span key={skill}>{skill}</span>)}</div>{user.role === "volunteer" ? <button className={joined ? "joined-btn" : "arrow-btn"} data-testid={`event-apply-${event.id}-button`} onClick={onApply} disabled={joined}>{joined ? <><Check size={14} /> {event.application}</> : <>Join event <ChevronRight size={16} /></>}</button> : <span className="capacity"><Users size={14} /> {event.volunteers}/{event.capacity}</span>}</div></article>; }

function Certificates({ certificates }) { return <section className="content-section standalone"><div className="section-head"><div><span className="eyebrow">YOUR IMPACT</span><h2>Certificates earned</h2><p className="section-sub">Every hour you give becomes part of your campus story.</p></div></div>{certificates.length ? <div className="certificate-grid">{certificates.map(cert => <div className="certificate" key={cert.event_id} data-testid={`certificate-${cert.event_id}`}><div className="cert-seal"><GraduationCap size={24} /></div><span className="eyebrow">CERTIFICATE OF COMPLETION</span><h3>{cert.title}</h3><p>Thank you for contributing <b>{cert.hours} hours</b> to your campus community.</p><a className="download-btn" data-testid={`certificate-download-${cert.event_id}`} href={`${API}/certificates/${cert.event_id}`} target="_blank" rel="noreferrer"><Download size={15} /> Download certificate</a></div>)}</div> : <div className="empty"><GraduationCap size={25} /><b>Your first certificate is waiting</b><span>Complete an event to see it here.</span></div>}</section>; }
function Manage({ apps, onUpdate, onComplete }) { return <section className="content-section standalone"><div className="section-head"><div><span className="eyebrow">ORGANIZER DESK</span><h2>Manage volunteers</h2><p className="section-sub">Review applications and celebrate the people who show up.</p></div></div><div className="app-table">{apps.length ? apps.map(app => <div className="app-row" key={`${app.event_id}-${app.username}`} data-testid={`applicant-row-${app.username}`}><div className="avatar">{app.name[0]}</div><div className="applicant"><b>{app.name}</b><span>{app.event_title} · {app.skills.join(" · ") || "Campus contributor"}</span></div><span className={`status ${app.status}`}>{app.status}</span>{app.status === "pending" && <div className="row-actions"><button data-testid={`accept-${app.username}-button`} onClick={() => onUpdate(app.event_id, app.username, "accepted")}><Check size={15} /></button><button data-testid={`reject-${app.username}-button`} onClick={() => onUpdate(app.event_id, app.username, "rejected")}><X size={15} /></button></div>}{app.status === "accepted" && <button className="complete-btn" data-testid={`complete-${app.username}-button`} onClick={() => onComplete(app.event_id, app.username)}>Mark complete <ChevronRight size={14} /></button>}</div>) : <div className="empty"><Users size={25} /><b>No applications yet</b><span>New volunteer applications will appear here.</span></div>}</div></section>; }

function CreateModal({ onClose, onCreate }) { const [data, setData] = useState({ title: "", description: "", date: "2025-10-04", time: "10:00 AM", location: "", capacity: 20 }); const [skills, setSkills] = useState(""); const update = (key, value) => setData({ ...data, [key]: value }); return <div className="modal-backdrop"><form className="modal" onSubmit={event => { event.preventDefault(); onCreate({ ...data, capacity: Number(data.capacity), required_skills: skills.split(",").map(item => item.trim()).filter(Boolean) }); }}><button type="button" className="modal-close" data-testid="close-create-modal-button" onClick={onClose}><X size={18} /></button><span className="eyebrow">NEW OPPORTUNITY</span><h2>Create a campus event</h2><Field label="Event title"><input data-testid="create-title-input" value={data.title} onChange={e => update("title", e.target.value)} required placeholder="e.g. Design thinking workshop" /></Field><Field label="Description"><textarea data-testid="create-description-input" value={data.description} onChange={e => update("description", e.target.value)} required placeholder="What will volunteers help make happen?" /></Field><div className="two-col"><Field label="Date"><input data-testid="create-date-input" type="date" value={data.date} onChange={e => update("date", e.target.value)} required /></Field><Field label="Time"><input data-testid="create-time-input" value={data.time} onChange={e => update("time", e.target.value)} required /></Field></div><div className="two-col"><Field label="Location"><input data-testid="create-location-input" value={data.location} onChange={e => update("location", e.target.value)} required placeholder="Student center" /></Field><Field label="Volunteer spots"><input data-testid="create-capacity-input" type="number" min="1" value={data.capacity} onChange={e => update("capacity", e.target.value)} required /></Field></div><Field label="Skills needed"><input data-testid="create-skills-input" value={skills} onChange={e => setSkills(e.target.value)} placeholder="Design, Communication" /></Field><button className="primary-btn full" data-testid="create-submit-button">Publish event <ChevronRight size={17} /></button></form></div>; }

export default App;